# Generated by Django 3.2.9 on 2021-11-29 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to='auth.user'),
            preserve_default=False,
        ),
    ]
