# Generated by Django 3.2.9 on 2021-12-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_owner'),
        ('spendings', '0002_spending_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to='categories.category'),
        ),
    ]
